# Prepare Demo 

Notebook to run to prepare data ready for demo.

In [10]:
import polars as pl
from pathlib import Path
import duckdb

from data_importers import WorldBankDataImporter
importer = WorldBankDataImporter()

In [11]:
DUCKDB_PATH = Path("../../databases") / "world_bank.db"
DUCKDB_PATH.parent.mkdir(parents=True, exist_ok=True)

if DUCKDB_PATH.exists():
    # Remove the file, we want to start from scratch
    DUCKDB_PATH.unlink()

In [12]:
START_YEAR = 1970
END_YEAR = 2024

SELECTED_COUNTRIES = [
    'GBR', 'FRA', 'DEU', 'ALB', 'NOR', 'GRC',   #Europe & Central Asia
    'JPN', 'CHN',                               #East Asia & Pacific
    'IND', 'PAK', 'BGD',                        #South Asia
    'SAU', 'EGY', 'ISR',                        #Middle East & North Africa
    'NGA', 'ZAF', 'TZA',                        #Sub-Saharan Africa
    'USA', 'CAN', 'MEX',                        #North America
    'CUB', 'DOM', 'CRI', 'BRA', 'ARG', 'CHL',   #Latin America & Caribbean
    'AUS', 'NZL', 'PHL', 'IDN', 'VNM', 'THA'    #East Asia & Pacific
]

SELECTED_INDICATORS = [
    'SP.POP.TOTL',          # Population, total
    'NY.GDP.MKTP.CD',       # GDP (current US$)
    'SE.ADT.LITR.ZS',       # Literacy rate, adult total
    'SL.UEM.TOTL.ZS',       # Unemployment, total (% of  total labor force)
    'SP.DYN.LE00.IN',       # Life expectancy at birth, total (years)
    'EG.USE.PCAP.KG.OE',    # Energy use per capita (kg of oil equivalent)
    'GC.DOD.TOTL.GD.ZS',    # Central government debt, total (% of GDP)
    'NY.GDP.PCAP.CD',       # GDP (US$, per capita)
]

## Get List of Countries

In [13]:
countries = importer.get_countries()

INFO:root:Fetching countries page 1...

In [14]:
countries.columns

['country_code',
 'iso2_code',
 'country_name',
 'region',
 'region_id',
 'income_level',
 'capital_city',
 'longitude',
 'latitude']

In [15]:
countries = countries.filter(pl.col("region") != "Aggregates")

In [16]:
# Cast longitude and latitude to double
countries = countries.with_columns(
    pl.col("longitude").cast(pl.Float64, strict=False),
    pl.col("latitude").cast(pl.Float64, strict=False)
)

In [17]:
countries.filter(pl.col("country_code").is_in(SELECTED_COUNTRIES))

shape: (32, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ country_c ┆ iso2_code ┆ country_n ┆ region    ┆ … ┆ income_le ┆ capital_c ┆ longitude ┆ latitude │
│ ode       ┆ ---       ┆ ame       ┆ ---       ┆   ┆ vel       ┆ ity       ┆ ---       ┆ ---      │
│ ---       ┆ str       ┆ ---       ┆ str       ┆   ┆ ---       ┆ ---       ┆ f64       ┆ f64      │
│ str       ┆           ┆ str       ┆           ┆   ┆ str       ┆ str       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ ALB       ┆ AL        ┆ Albania   ┆ Europe &  ┆ … ┆ Upper     ┆ Tirane    ┆ 19.8172   ┆ 41.3317  │
│           ┆           ┆           ┆ Central   ┆   ┆ middle    ┆           ┆           ┆          │
│           ┆           ┆           ┆ Asia      ┆   ┆ income    ┆           ┆           ┆          │
│ ARG       ┆ AR        ┆ Argentina ┆ Latin     ┆ … ┆ Upper     ┆ Buenos    ┆ -58.4173  ┆ -34.6118 │
│           ┆           ┆           ┆ America & ┆   ┆ middle    ┆ Aires     ┆           ┆          │
│           ┆           ┆           ┆ Caribbean ┆   ┆ income    ┆           ┆           ┆          │
│ AUS       ┆ AU        ┆ Australia ┆ East Asia ┆ … ┆ High      ┆ Canberra  ┆ 149.129   ┆ -35.282  │
│           ┆           ┆           ┆ & Pacific ┆   ┆ income    ┆           ┆           ┆          │
│ BGD       ┆ BD        ┆ Banglades ┆ South     ┆ … ┆ Lower     ┆ Dhaka     ┆ 90.4113   ┆ 23.7055  │
│           ┆           ┆ h         ┆ Asia      ┆   ┆ middle    ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ income    ┆           ┆           ┆          │
│ BRA       ┆ BR        ┆ Brazil    ┆ Latin     ┆ … ┆ Upper     ┆ Brasilia  ┆ -47.9292  ┆ -15.7801 │
│           ┆           ┆           ┆ America & ┆   ┆ middle    ┆           ┆           ┆          │
│           ┆           ┆           ┆ Caribbean ┆   ┆ income    ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ THA       ┆ TH        ┆ Thailand  ┆ East Asia ┆ … ┆ Upper     ┆ Bangkok   ┆ 100.521   ┆ 13.7308  │
│           ┆           ┆           ┆ & Pacific ┆   ┆ middle    ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ income    ┆           ┆           ┆          │
│ TZA       ┆ TZ        ┆ Tanzania  ┆ Sub-Sahar ┆ … ┆ Lower     ┆ Dodoma    ┆ 35.7382   ┆ -6.17486 │
│           ┆           ┆           ┆ an Africa ┆   ┆ middle    ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ income    ┆           ┆           ┆          │
│ USA       ┆ US        ┆ United    ┆ North     ┆ … ┆ High      ┆ Washingto ┆ -77.032   ┆ 38.8895  │
│           ┆           ┆ States    ┆ America   ┆   ┆ income    ┆ n D.C.    ┆           ┆          │
│ VNM       ┆ VN        ┆ Viet Nam  ┆ East Asia ┆ … ┆ Lower     ┆ Hanoi     ┆ 105.825   ┆ 21.0069  │
│           ┆           ┆           ┆ & Pacific ┆   ┆ middle    ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ income    ┆           ┆           ┆          │
│ ZAF       ┆ ZA        ┆ South     ┆ Sub-Sahar ┆ … ┆ Upper     ┆ Pretoria  ┆ 28.1871   ┆ -25.746  │
│           ┆           ┆ Africa    ┆ an Africa ┆   ┆ middle    ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ income    ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## Download indicator data

For each country, for each indicator between the years chosen.

In [18]:
data = importer.get_data(
    indicators=SELECTED_INDICATORS,
    countries=SELECTED_COUNTRIES,
    start_year=START_YEAR,
    end_year=END_YEAR
)

INFO:root:Fetching data with skip=0...
INFO:root:Fetching data with skip=1000...
INFO:root:Fetching data with skip=2000...
INFO:root:Fetching data with skip=3000...
INFO:root:Fetching data with skip=4000...
INFO:root:Fetching data with skip=5000...
INFO:root:Fetching data with skip=6000...
INFO:root:Fetching data with skip=7000...
INFO:root:Fetching data with skip=8000...
INFO:root:Fetching data with skip=9000...

In [19]:
data

shape: (9_778, 4)
┌──────────────┬──────┬──────────────────────────┬─────────────┐
│ country_code ┆ year ┆ indicator_code           ┆ value       │
│ ---          ┆ ---  ┆ ---                      ┆ ---         │
│ str          ┆ i64  ┆ str                      ┆ f64         │
╞══════════════╪══════╪══════════════════════════╪═════════════╡
│ VNM          ┆ 1999 ┆ WB_WDI_EG_USE_PCAP_KG_OE ┆ 358.075426  │
│ VNM          ┆ 2001 ┆ WB_WDI_EG_USE_PCAP_KG_OE ┆ 393.081627  │
│ VNM          ┆ 2008 ┆ WB_WDI_EG_USE_PCAP_KG_OE ┆ 572.099542  │
│ VNM          ┆ 2007 ┆ WB_WDI_EG_USE_PCAP_KG_OE ┆ 544.673183  │
│ USA          ┆ 2000 ┆ WB_WDI_EG_USE_PCAP_KG_OE ┆ 8055.145489 │
│ …            ┆ …    ┆ …                        ┆ …           │
│ MEX          ┆ 1970 ┆ WB_WDI_SP_POP_TOTL       ┆ 5.0814953e7 │
│ NZL          ┆ 1970 ┆ WB_WDI_SP_POP_TOTL       ┆ 2.8107e6    │
│ NGA          ┆ 1970 ┆ WB_WDI_SP_POP_TOTL       ┆ 5.5893838e7 │
│ NOR          ┆ 1970 ┆ WB_WDI_SP_POP_TOTL       ┆ 3.875763e6  │
│ ALB          ┆ 1975 ┆ WB_WDI_SP_POP_TOTL       ┆ 2.404831e6  │
└──────────────┴──────┴──────────────────────────┴─────────────┘

## Capture indicator metadata

In [20]:
indicators = importer.get_indicator_metadata(indicators=SELECTED_INDICATORS)
indicators

INFO:root:Fetching metadata for 8 indicators...

shape: (8, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ indicator_ ┆ indicator_ ┆ aggregatio ┆ definitio ┆ statistic ┆ methodolo ┆ limitatio ┆ relevance │
│ code       ┆ name       ┆ n_method   ┆ n_long    ┆ al_concep ┆ gy        ┆ n         ┆ ---       │
│ ---        ┆ ---        ┆ ---        ┆ ---       ┆ t         ┆ ---       ┆ ---       ┆ str       │
│ str        ┆ str        ┆ str        ┆ str       ┆ ---       ┆ str       ┆ str       ┆           │
│            ┆            ┆            ┆           ┆ str       ┆           ┆           ┆           │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ WB_WDI_NY_ ┆ GDP per    ┆ Weighted   ┆ Gross     ┆ The conce ┆ National  ┆ null      ┆ This      │
│ GDP_PCAP_C ┆ capita     ┆ average    ┆ domestic  ┆ ptual     ┆ accounts  ┆           ┆ indicator │
│ D          ┆ (current   ┆            ┆ product   ┆ elements  ┆ are       ┆           ┆ is        │
│            ┆ US$)       ┆            ┆ is the …  ┆ of the…   ┆ compiled… ┆           ┆ related   │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ to t…     │
│ WB_WDI_GC_ ┆ Central    ┆ Weighted   ┆ Debt is   ┆ Governmen ┆ Governmen ┆ For most  ┆ This      │
│ DOD_TOTL_G ┆ government ┆ average    ┆ the       ┆ t         ┆ t Finance ┆ countries ┆ indicator │
│ D_ZS       ┆ debt,      ┆            ┆ entire    ┆ Financial ┆ statistic ┆ central   ┆ is        │
│            ┆ total…     ┆            ┆ stock of  ┆ Statistic ┆ s …       ┆ gov…      ┆ related   │
│            ┆            ┆            ┆ di…       ┆ …         ┆           ┆           ┆ to G…     │
│ WB_WDI_SP_ ┆ Life       ┆ Weighted   ┆ Life expe ┆ Life expe ┆ Life expe ┆ Annual    ┆ Mortality │
│ DYN_LE00_I ┆ expectancy ┆ average    ┆ ctancy at ┆ ctancy at ┆ ctancy at ┆ data      ┆ rates for │
│ N          ┆ at birth,  ┆            ┆ birth     ┆ birth     ┆ birth is  ┆ series    ┆ different │
│            ┆ tota…      ┆            ┆ indic…    ┆ used …    ┆ de…       ┆ from      ┆ …         │
│            ┆            ┆            ┆           ┆           ┆           ┆ United…   ┆           │
│ WB_WDI_SL_ ┆ Unemployme ┆ Weighted   ┆ Unemploym ┆ The unemp ┆ The unemp ┆ While the ┆ The unemp │
│ UEM_TOTL_Z ┆ nt, total  ┆ average    ┆ ent       ┆ loyed     ┆ loyment   ┆ unemploym ┆ loyment   │
│ S          ┆ (% of      ┆            ┆ refers to ┆ comprise  ┆ rate is   ┆ ent rate  ┆ rate is a │
│            ┆ tota…      ┆            ┆ the sha…  ┆ all pe…   ┆ calcu…    ┆ ma…       ┆ use…      │
│ WB_WDI_SP_ ┆ Population ┆ Sum        ┆ Total pop ┆ Estimates ┆ Populatio ┆ Current   ┆ Increases │
│ POP_TOTL   ┆ , total    ┆            ┆ ulation   ┆ of total  ┆ n         ┆ populatio ┆ in human  │
│            ┆            ┆            ┆ is based  ┆ populatio ┆ estimates ┆ n         ┆ populatio │
│            ┆            ┆            ┆ on t…     ┆ n …       ┆ are       ┆ estimates ┆ n,…       │
│            ┆            ┆            ┆           ┆           ┆ usual…    ┆ f…        ┆           │
│ WB_WDI_SE_ ┆ Literacy   ┆ Weighted   ┆ Adult     ┆ Literacy  ┆ The       ┆ In        ┆ Literacy  │
│ ADT_LITR_Z ┆ rate,      ┆ average    ┆ literacy  ┆ statistic ┆ indicator ┆ practice, ┆ rate is   │
│ S          ┆ adult      ┆            ┆ rate is   ┆ s for     ┆ is calcul ┆ literacy  ┆ an        │
│            ┆ total (% … ┆            ┆ the per…  ┆ most c…   ┆ ated by…  ┆ is diffi… ┆ outcome   │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ in…       │
│ WB_WDI_EG_ ┆ Energy use ┆ Weighted   ┆ Energy    ┆ null      ┆ Total     ┆ The IEA   ┆ In develo │
│ USE_PCAP_K ┆ (kg of oil ┆ average    ┆ use       ┆           ┆ energy    ┆ makes     ┆ ping      │
│ G_OE       ┆ equivale…  ┆            ┆ refers to ┆           ┆ use       ┆ these     ┆ economies │
│            ┆            ┆            ┆ use of    ┆           ┆ refers to ┆ estimates ┆ growth…   │
│            ┆            ┆            ┆ pr…       ┆           ┆ the…      ┆ …         ┆           │
│ WB_WDI_NY_ ┆ GDP        ┆ Gap-filled ┆ Gross     ┆ The conce ┆ National  ┆ Gross     ┆ This      │
│ GDP_MKTP_C ┆ (current   ┆ total      ┆ domestic  ┆ ptual     ┆ accounts  ┆ domestic  ┆ indicator │
│ D          ┆ US$)       ┆            ┆ product   ┆ elements  ┆ are       ┆ product   ┆ is        │
│            ┆            ┆            ┆ is the …  ┆ of the…   ┆ compiled… ┆ (GDP), …  ┆ related   │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ to t…     │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

## DuckDB

In [21]:
with duckdb.connect(DUCKDB_PATH) as db:

    db.sql("CREATE SCHEMA IF NOT EXISTS silver;")

    db.sql(
        f"""
        CREATE OR REPLACE TABLE silver.countries AS
        SELECT *
        FROM countries;
        """
    )

    db.sql(
        f"""
        CREATE OR REPLACE TABLE silver.data AS
        SELECT *
        FROM data;
        """
    )

    db.sql(
        f"""
        CREATE OR REPLACE TABLE silver.indicators AS
        SELECT *
        FROM indicators;
        """
    )

db.close()